[package]
name = "bevy_mod_loader"
version = "0.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.5.0"
bevy_log = "0.5.0"
libloading = "0.7.0"


[features]
modio = []
steam = []